In this file, I will write my solutions and some notes about [numpy-100 repository](https://github.com/rougier/numpy-100?tab=MIT-1-ov-file). Sure the solution will be same but with the differenc way.<br/>
You can watch this vidio by [KEITH GALI](https://www.youtube.com/watch?v=PM504XhEVCU&t=2404s) if you want.

1. Import the numpy package under the name np

In [47]:
import numpy as np

2. Print the numpy version and the configuration

In [48]:
print(np.__version__)
print(np.show_config())

2.4.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuratio

3. Create a null vector of size 10

In [49]:
# Return a float array, but you can change its type by `dtype=`
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array

In [50]:
arr = np.arange(5, 11)
# Return how many numbers in the array
items = np.size(arr)
# Return the size of one number (because all have same size)
size_of_item = arr.itemsize
memory_size = items * size_of_item
memory_size

48

5. How to get the documentation of the numpy add function from the command line? 

6. Create a null vector of size 10 but the fifth value which is 1

In [51]:
arr = np.zeros(10, dtype=int)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49

In [52]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last)

In [53]:
print(arr[::-1])
# or by using the flip() function
print(np.flip(arr))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [54]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [57]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)

(array([0, 1, 4]),)