### In this file, I will write my solutions and some notes on the first 30 questions in [the numpy-100 repository](https://github.com/rougier/numpy-100?tab=MIT-1-ov-file)..
### You can watch this vidio by  if you want.
### You can watch this video by [KEITH GALI](https://www.youtube.com/watch?v=PM504XhEVCU&t=2404s) if you want.

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [48]:
print(np.__version__)
print(np.show_config())

2.4.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuratio

3. Create a null vector of size 10

In [49]:
# Return a float array, but you can change its type by `dtype=`
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array

In [50]:
arr = np.arange(5, 11)
# Return how many numbers in the array
items = np.size(arr)
# Return the size of one number (because all have same size)
size_of_item = arr.itemsize
memory_size = items * size_of_item
memory_size

48

5. How to get the documentation of the numpy add function from the command line? 

In [3]:
np.add?
# There are many way to write this code.

Signature:      
np.add(
    x1,
    x2,
    /,
    out=None,
    *,
    where=True,
    casting='same_kind',
    order='K',
    dtype=None,
    subok=True,
    signature=None,
)
Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\hp\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a


6. Create a null vector of size 10 but the fifth value which is 1

In [51]:
arr = np.zeros(10, dtype=int)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49

In [52]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last)

In [53]:
print(arr[::-1])
# or by using the flip() function
print(np.flip(arr))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [54]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [3]:
arr = np.array([1,2,0,0,4,0])
print(np.where(arr != 0))
# or 
print(np.nonzero(arr))

(array([0, 1, 4]),)
(array([0, 1, 4]),)


11. Create a 3x3 identity matrix

In [4]:
print(np.identity(3))
# or
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- **The difference between np.identity() and np.eye()**<br/>
In NumPy, `identity` creates a square identity matrix only, while `eye` creates an identity-like matrix of any shape.<br/>
    - np.identity(n) → always **n × n**<br/>
    - np.eye(n, m) → **n × m** (more flexible)

12. Create a 3x3x3 array with random values 

In [5]:
arr = np.random.randint(0, 10, (3, 3, 3))
arr

array([[[9, 5, 8],
        [8, 9, 5],
        [7, 4, 8]],

       [[6, 4, 6],
        [2, 4, 4],
        [8, 8, 8]],

       [[4, 6, 4],
        [9, 8, 9],
        [6, 9, 4]]], dtype=int32)

13. Create a 10x10 array with random values and find the minimum and maximum values 

In [13]:
arr = np.random.random((10, 10))
f"The minimum value is {arr.min()} and the maximum value is {arr.max()}"

'The minimum value is 0.02722128327012663 and the maximum value is 0.9851631623735052'

14. Create a random vector of size 30 and find the mean value

In [14]:
arr = np.random.uniform(1, 20, 30)
# This function give a random float numbers between two numbers
arr.mean()

np.float64(11.245910342096268)

15. Create a 2d array with 1 on the border and 0 inside

In [15]:
rows = int(input("Enter how many rows do you want: "))
columns = int(input("Enter how many columns do you want: "))
arr = np.ones((rows, columns), dtype=int)
arr[1:-1, 1:-1] = 0
print(f"So your 2D array with 1 on the border and 0 inside is:\n {arr}")

Enter how many rows do you want:  3
Enter how many columns do you want:  7


So your 2D array with 1 on the border and 0 inside is:
 [[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


16. How to add a border (filled with 0's) around an existing array? 

In [17]:
# We use the `np.pad()` function
np.pad(arr, pad_width=1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

17. What is the result of the following expression?<br/>
0 * np.nan<br/>
np.nan == np.nan<br/>
np.inf > np.nan<br/>
np.nan - np.nan<br/>
np.nan in set([np.nan])<br/>
0.3 == 3 * 0.1

In [6]:
# In this exrecise only print the lines, after I going to guess the result
"""
0
True
False
NaN
True
True
"""
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
arr = np.zeros((5, 5), dtype=int)
diagonal = np.arange(1, 5)
arr[[diagonal], [diagonal - 1]] = diagonal
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
arr = np.ones((8, 8), dtype=int)
arr[::2, ::2] = 0
arr[1::2, 1::2] = 0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [5]:
np.unravel_index(99,  (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

21. Create a checkerboard 8x8 matrix using the tile function 

In [16]:
# More information about `np.tile()`
np.tile?
arr = np.array([0, 1])
arr1 = np.tile(arr, 4)
arr2 = arr1[::-1]
np.tile((arr1, arr2), (4, 1))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

22. Normalize a 5x5 random matrix

In [21]:
# Normalize is a transformation, that rescale the value. Keep the shape of the data but change its scale.
arr = np.arange(1, 26).reshape(5, 5)
norml_arr = (arr-arr.mean())/(arr.std())
print(norml_arr)

[[-1.66410059 -1.52542554 -1.38675049 -1.24807544 -1.10940039]
 [-0.97072534 -0.83205029 -0.69337525 -0.5547002  -0.41602515]
 [-0.2773501  -0.13867505  0.          0.13867505  0.2773501 ]
 [ 0.41602515  0.5547002   0.69337525  0.83205029  0.97072534]
 [ 1.10940039  1.24807544  1.38675049  1.52542554  1.66410059]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [27]:
# new information

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [30]:
arr1 = np.random.randint(1, 10, (5, 3))
arr2 = np.random.randint(1, 10, (3, 2))
np.matmul(arr1, arr2)

array([[ 77, 119],
       [ 28,  46],
       [ 89, 131],
       [ 71,  98],
       [ 58, 106]], dtype=int32)

25. Given a 1D array, negate all elements which are between 3 and 8.

In [39]:
np.random.seed(42)
arr = np.random.randint(1, 10, 20)
np.where((arr > 3) & (arr < 8), arr*-1, arr)

array([-7, -4,  8, -5, -7,  3, -7,  8, -5, -4,  8,  8,  3, -6, -5,  2,  8,
       -6,  2, -5], dtype=int32)

26. What is the output of the following script?<br/>
print(sum(range(5),-1))<br/>
from numpy import *<br/>
print(sum(range(5),-1))

In [ ]:
# 10 solution is 9
# 10

28. What are the result of the following expressions? <br/>
np.array(0) / np.array(0) <br/>
np.array(0) // np.array(0) <br/>
np.array([np.nan]).astype(int).astype(float)

In [ ]:
# NaN
# 0
# 0.0

30. How to find common values between two arrays?

In [43]:
arr1 = np.array([5,3,8,2,0,3,6])
arr2 = np.array([7,0,8,4,0,3,6])
arr2[np.where(arr1 == arr2)]

array([8, 0, 3, 6])