In this file, I will write my solutions and some notes about [numpy-100 repository](https://github.com/rougier/numpy-100?tab=MIT-1-ov-file). Sure the result will be same but with the different way.<br/>
You can watch this vidio by [KEITH GALI](https://www.youtube.com/watch?v=PM504XhEVCU&t=2404s) if you want.

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [48]:
print(np.__version__)
print(np.show_config())

2.4.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuratio

3. Create a null vector of size 10

In [49]:
# Return a float array, but you can change its type by `dtype=`
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array

In [50]:
arr = np.arange(5, 11)
# Return how many numbers in the array
items = np.size(arr)
# Return the size of one number (because all have same size)
size_of_item = arr.itemsize
memory_size = items * size_of_item
memory_size

48

5. How to get the documentation of the numpy add function from the command line? 

In [ ]:
?

6. Create a null vector of size 10 but the fifth value which is 1

In [51]:
arr = np.zeros(10, dtype=int)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49

In [52]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last)

In [53]:
print(arr[::-1])
# or by using the flip() function
print(np.flip(arr))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [54]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [3]:
arr = np.array([1,2,0,0,4,0])
print(np.where(arr != 0))
# or 
print(np.nonzero(arr))

(array([0, 1, 4]),)
(array([0, 1, 4]),)


11. Create a 3x3 identity matrix

In [4]:
print(np.identity(3))
# or
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- **The difference between np.identity() and np.eye()**<br/>
In NumPy, `identity` creates a square identity matrix only, while `eye` creates an identity-like matrix of any shape.<br/>
    - np.identity(n) → always **n × n**<br/>
    - np.eye(n, m) → **n × m** (more flexible)

12. Create a 3x3x3 array with random values 

In [5]:
arr = np.random.randint(0, 10, (3, 3, 3))
arr

array([[[9, 5, 8],
        [8, 9, 5],
        [7, 4, 8]],

       [[6, 4, 6],
        [2, 4, 4],
        [8, 8, 8]],

       [[4, 6, 4],
        [9, 8, 9],
        [6, 9, 4]]], dtype=int32)

13. Create a 10x10 array with random values and find the minimum and maximum values 

In [13]:
arr = np.random.random((10, 10))
f"The minimum value is {arr.min()} and the maximum value is {arr.max()}"

'The minimum value is 0.02722128327012663 and the maximum value is 0.9851631623735052'

14. Create a random vector of size 30 and find the mean value

In [14]:
arr = np.random.uniform(1, 20, 30)
# This function give a random float numbers between two numbers
arr.mean()

np.float64(11.245910342096268)

15. Create a 2d array with 1 on the border and 0 inside

In [15]:
rows = int(input("Enter how many rows do you want: "))
columns = int(input("Enter how many columns do you want: "))
arr = np.ones((rows, columns), dtype=int)
arr[1:-1, 1:-1] = 0
print(f"So your 2D array with 1 on the border and 0 inside is:\n {arr}")

Enter how many rows do you want:  3
Enter how many columns do you want:  7


So your 2D array with 1 on the border and 0 inside is:
 [[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


16. How to add a border (filled with 0's) around an existing array? 

In [17]:
# We use the `np.pad()` function
np.pad(arr, pad_width=1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])