### Welcome to this **NumPy exercises solution book.**

### 1. Array Creation & Fundamentals: 

In [2]:
# 1
import numpy as np

In [2]:
# 2
print(np.__version__)

2.4.0


In [3]:
# 3
arr_f = np.zeros(10)
# Convert to integer data
arr_i = np.zeros(10, dtype=int)
print(arr_f)
print(arr_i)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [5]:
# 4
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#5
x = np.array([2,3,5,6])
print(np.ones(x.shape, dtype=int))
# or
print(np.ones_like(x))
# or
print(np.full_like(x, 1))
# or
print(np.full(x.shape, 1))

[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]


In [7]:
# 6
arr = np.array([0,8,5,0,9], dtype=bool)
arr

array([False,  True,  True, False,  True])

In [9]:
# 7
# There are many way to create a numpy tensor.
arr_tens = np.array([[[1,2], [3,4]], [[5,6], [7, 8]]])
print(arr_tens)
print(arr_tens.ndim)
print(arr_tens.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


### 2. Indexing, Slicing & Selection: 

In [13]:
# 8
arr = np.array([1,4,6,8,2,3,4,5,8,3])
odd_numbers = arr[arr % 2 == 1]
odd_numbers

array([1, 3, 5, 3])

In [14]:
# 9
arr[odd_numbers] = -1
arr

array([ 1, -1,  6, -1,  2, -1,  4,  5,  8,  3])

In [20]:
# 10
x = np.array([1,2,3,4,5])
print(x[0])

1


In [21]:
# 11
x[1:-1]

array([2, 3, 4])

### 3. Reshaping:

In [25]:
# 12
arr = np.arange(11, 21).reshape(2, -1)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
# 13
arr1 = np.array([1,2,3])
arr2 = np.arange(2, 5)
np.stack([arr1, arr2])

array([[1, 2, 3],
       [2, 3, 4]])

### 4. Joining NumPy Arrays:

In [27]:
# 14
np.concat([arr1, arr2])

array([1, 2, 3, 2, 3, 4])

### 5. Searching Arrays: 

In [32]:
# 15
arr = np.array([-2,6,9,-9,6,-4,-3,3,4,-5])
arr[arr < 0]

array([-2, -9, -4, -3, -5])

In [7]:
# 16
np.random.seed(42)
y = np.random.randint(1, 10, (3, 4))
y[y >= 5]

array([7, 8, 5, 7, 7, 8, 5, 8, 8], dtype=int32)

In [26]:
# 17
arr1 = np.array([5,3,2,0,7,5,4])
arr2 = np.array([9,3,2,1,4,5,6])
np.where(arr1 == arr2)

(array([1, 2, 5]),)

In [25]:
# 18
x = np.arange(1, 5) + 5
x

array([6, 7, 8, 9])

In [23]:
# 19
np.random.seed(42)
arr = np.random.randint(1, 15, (3, 4))
arr[(arr > 5) & (arr < 10)]

array([7, 8, 7, 7], dtype=int32)

In [30]:
# 20
y = np.array([6,8,5,3,1,0,6,5])
print(f"The numbers higher than the elements mean are: {y[y > y.mean()]}")

The numbers higher than the elements mean are: [6 8 5 6 5]


### 6. Sorting Arrays:

In [21]:
# 21
arr = np.array([4,3,-9,2,7,-3,0,1])
np.sort(arr)

array([-9, -3,  0,  1,  2,  3,  4,  7])

### 7. Random Numbers in NumPy:

In [12]:
# 22
np.random.seed(42)
arr = np.random.uniform(5, 10, (5, 3))
arr

array([[6.87270059, 9.75357153, 8.65996971],
       [7.99329242, 5.7800932 , 5.7799726 ],
       [5.29041806, 9.33088073, 8.00557506],
       [8.54036289, 5.10292247, 9.84954926],
       [9.1622132 , 6.06169555, 5.90912484]])

In [17]:
# 23
np.random.seed(42)
np.set_printoptions(precision=2)
float_arr = np.random.random((3, 3, 3))
float_arr

array([[[0.37, 0.95, 0.73],
        [0.6 , 0.16, 0.16],
        [0.06, 0.87, 0.6 ]],

       [[0.71, 0.02, 0.97],
        [0.83, 0.21, 0.18],
        [0.18, 0.3 , 0.52]],

       [[0.43, 0.29, 0.61],
        [0.14, 0.29, 0.37],
        [0.46, 0.79, 0.2 ]]])

In [18]:
# 24
np.random.randint(-10, 10, 5) 

array([ 9, -8, -6,  8, -4], dtype=int32)

### 8. Operation Math: 

In [28]:
# 25
z = np.random.randint(1, 10, (4, 2))
# sum of all elements
print(np.sum(z))
# sum of all rows
print(np.sum(z, axis=1))
# sum of all columns
print(np.sum(z, axis=0))

53
[ 6 12 18 17]
[31 22]


In [40]:
# 26
print(np.mean(z))

4.5


In [47]:
# 27
x = np.arange(1, 13).reshape(3, -1)
print(x)
print(np.sum(x, axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[15 18 21 24]


In [45]:
# 28
print(np.mean(x, axis=1))

[ 2.5  6.5 10.5]


In [46]:
# 29
print(np.max(x))

12


In [48]:
# 30
print(np.min(x, axis=1))

[1 5 9]
