## Welcome to this **second NumPy exercise solution book**

In [2]:
# 1
import numpy as np

In [4]:
np.__version__

'2.4.0'

In [8]:
# 2
arr = np.array([8,4,5,3,1,3,6])
print(arr)
# The shape of this array
print(arr.shape)
# Number of dimension 
arr.ndim

[8 4 5 3 1 3 6]
(7,)


1

In [17]:
# 3
arr = np.array([0,5,3,0,8,7], dtype=bool)
print(arr)
arr = np.full((2, 2), True, dtype=bool)
print(arr)

[False  True  True False  True  True]
[[ True  True]
 [ True  True]]


In [19]:
# 4
arr = np.arange(1, 11)
arr[::2]

array([1, 3, 5, 7, 9])

In [20]:
# 5
arr[::2] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [26]:
# 6
arr_1D = np.arange(10, 30)
print(arr_1D.ndim)
arr_2D = arr_1D.reshape(2, -1)
print(arr_2D.ndim)

1
2


In [27]:
# 7
a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.full((2, 4), 1)
print(np.vstack((a, b)))

[[1 2 3 4]
 [5 6 7 8]
 [1 1 1 1]
 [1 1 1 1]]


In [28]:
# 8
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


In [29]:
# 9
arr1 = np.arange(1, 6)
arr2 = np.arange(5, 10)
print(np.setdiff1d(arr1, arr2))

[1 2 3 4]


In [30]:
# 10
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(x == y)

(array([1, 3, 5, 7]),)

In [33]:
# 11
a = np.array([-6,5,9,8,3,40,1,6])
(a[(a < 10) & (a > 5)])

array([9, 8, 6])

In [34]:
# 12
def pair_max(a, b):
    return np.max((a,b), axis=0)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [39]:
# 13
arr = np.arange(9).reshape(3,3)
print(arr[::-1])
"---------"
# or
print(np.flip(arr))

[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[8 7 6]
 [5 4 3]
 [2 1 0]]


In [44]:
# 14
np.random.uniform(5, 10, (5, 3))

array([[6.33933359, 5.77751751, 5.56340798],
       [9.82259112, 9.19049833, 9.00618446],
       [7.23051786, 5.51707075, 7.90152884],
       [6.15058913, 7.96494712, 9.7741988 ],
       [5.0081884 , 6.49230278, 7.88118519]])

In [45]:
# 15
arr = np.array([6,9,18,30,1,9,35])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

15.428571428571429
9.0
11.84250387203583
