### Welcome to this **first NumPy exercise solution book.**

In [1]:
# 1
import numpy as np

In [2]:
# 2
print(np.__version__)

2.4.0


In [4]:
# 3
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 4
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# 5
arr = np.ones((2, 2), dtype=int)
print(arr)

[[1 1]
 [1 1]]


In [8]:
# 6
arr = np.ones((3, 2), dtype=float)
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
#7
x = np.array([2,3,5,6])
print(np.ones(x.shape, dtype=int))
# or
print(np.full_like(x, 1))
# or
print(np.full(x.shape, 1))

[1 1 1 1]
[1 1 1 1]
[1 1 1 1]


In [17]:
# 8
x = np.array([[3.7, 2], [7, 6]])
print(np.zeros(x.shape, dtype=float))

[[0 0]
 [0 0]]


In [20]:
# 9
arr = np.array([[1,2,3,4], [5,6,7,8], [5,4,1,5], [6,5,0,9]])
print(np.full_like(arr, 5))
# or
print(np.ones_like(arr)* 5)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [5]:
# 10
arr_ident = np.identity(3)
print(arr_ident)
# or
arr_eye = np.eye(3, 3, dtype=int)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


What is the difference between **eye()** and **identity()**?<br/>
In NumPy, **identity** creates a square identity matrix only, while **eye** creates an identity-like matrix of any shape.<br/>
In one line:
- np.identity(n) → always **n × n**
- np.eye(n, m) → **n × m** (more flexible)

In [6]:
# 11
arr = np.random.randint(0, 11, 3)
print(arr)

[6 7 1]


In [9]:
# 12
arr_3D = np.random.rand(3, 3, 3)
print(arr_3D)
# We can control the numbers after comma by `np.set_printoption()`
np.set_printoptions(precision = 3)
print(arr_3D)

[[[0.13111772 0.34518922 0.46915416]
  [0.7509399  0.96513244 0.398811  ]
  [0.58828262 0.35175195 0.00937213]]

 [[0.91778484 0.45342988 0.47918563]
  [0.60424314 0.87045111 0.5244834 ]
  [0.24264998 0.30738271 0.86953315]]

 [[0.78931239 0.81654048 0.6950213 ]
  [0.16085659 0.56416455 0.48172534]
  [0.75544739 0.94360741 0.46592032]]]
[[[0.131 0.345 0.469]
  [0.751 0.965 0.399]
  [0.588 0.352 0.009]]

 [[0.918 0.453 0.479]
  [0.604 0.87  0.524]
  [0.243 0.307 0.87 ]]

 [[0.789 0.817 0.695]
  [0.161 0.564 0.482]
  [0.755 0.944 0.466]]]


In [10]:
# 13
x = [4,5,7,5]
print(type(x))
y = np.array(x)
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
# 14
arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


In [13]:
# 15
arr = np.arange(10, 0, -1)
print(arr)
# or
arr = np.arange(1, 11)[::-1]
print(arr)

[10  9  8  7  6  5  4  3  2  1]
[10  9  8  7  6  5  4  3  2  1]


In [14]:
# 16
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# 17
z = np.array([4,5,3,1])
memory_size = z.itemsize * np.size(z)
print(f"the memory size of the z numpy array is {memory_size}")

the memory size of the z numpy array is 32


In [22]:
# 18
x = np.array([3,6,9,0,8,6])
print(f"The first element is {x[0]} and the last element {x[-1]}")

The first element is 3 and the last element 6


In [23]:
# 19
print(f"The first three elements n X numpy array: {x[:3]}")

The first three elements n X numpy array: [3 6 9]


In [24]:
# 20
print(f"And all middle elements are {x[1:-1]}")

And all middle elements are [6 9 0 8]


In [3]:
# 21
x = np.array([4,6,8,0,8,5,2])
print(x[1::2])

[6 0 5]


In [9]:
# 22
x_matrix = np.array([[2,3,4],[8,7,6], [5,4,0]])
print(x_matrix[0])

[2 3 4]


In [10]:
# 23
print(x_matrix[-1])

[5 4 0]


In [11]:
# 24
print(x_matrix[0, 0])

2


In [12]:
# 25
print(x_matrix[-1, 0])

5


In [17]:
# 26
print(x_matrix[:2, -2:])

[[3 4]
 [7 6]]


In [22]:
# 27
print(np.sort(x_matrix))

[[2 3 4]
 [6 7 8]
 [0 4 5]]


In [25]:
# 28
x = np.arange(45, 55)
print(f"Befor changing: {x}")
# if you don't want the index of number 50
x[np.where(x == 50)] = 40
print(f"After changing: {x}")
# or if you want the index of number 50
x[5] = 40
print(x)

Befor changing: [45 46 47 48 49 50 51 52 53 54]
After changing: [45 46 47 48 49 40 51 52 53 54]
[45 46 47 48 49 40 51 52 53 54]


In [26]:
# 29
x = np.random.randint(1, 10, (4, 3))
x[-1, :] = 1
print(x)

[[2 2 5]
 [8 2 7]
 [7 7 2]
 [1 1 1]]


In [28]:
# 30
print(x + 5)
# or
print(np.add(x, 5))

[[ 7  7 10]
 [13  7 12]
 [12 12  7]
 [ 6  6  6]]
[[ 7  7 10]
 [13  7 12]
 [12 12  7]
 [ 6  6  6]]


In [34]:
# 31
y = np.random.randint(-5, 10, 10)
print(f"My array is{y}\nAfter filtring negative elements, the result is {y[y < 0]}")

My array is[ 2  2  6  0 -5 -3 -2  6  5 -4]
After filtring negative elements, the result is [-5 -3 -2 -4]


In [37]:
# 32
print(f"The numbers highter than 5 are: {y[y > 5]}")

The numbers highter than 5 are: [6 6]


In [38]:
# 33
print(f"The numbers higher than the elements mean are: {y[y > y.mean()]}")

The numbers higher than the elements mean are: [2 2 6 6 5]


In [39]:
# 34
z = np.random.randint(1, 10, (4, 2))
# sum of all elements
print(np.sum(z))
# sum of all rows
print(np.sum(z, axis=1))
# sum of all columns
print(np.sum(z, axis=0))

36
[ 9  5 11 11]
[12 24]


In [40]:
# 35
print(np.mean(z))

4.5


In [47]:
x = np.arange(1, 13).reshape(3, -1)
print(x)
# 36
print(np.sum(x, axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[15 18 21 24]


In [45]:
# 37
print(np.mean(x, axis=1))

[ 2.5  6.5 10.5]


In [46]:
# 38
print(np.max(x))

12


In [48]:
# 39
print(np.min(x, axis=1))

[1 5 9]
